{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secrets
  namespace: {{ .Values.keycloak.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: keycloak-secrets
  data:
    - secretKey: db-username
      remoteRef:
        key: keycloak/database
        property: username
    - secretKey: db-password
      remoteRef:
        key: keycloak/database
        property: password
    - secretKey: admin-user
      remoteRef:
        key: keycloak/database
        property: admin_username
    - secretKey: admin-password
      remoteRef:
        key: keycloak/database
        property: admin_password
{{- end }}