{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/instance: gateway
    app.kubernetes.io/managed-by: Helm
{{- end }}